# -*- coding: utf-8 -*-
"""Webcam_App-using_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16BtBD64GuNER4HAEbjARKWu8RDxK9AI4
"""

import cv2, time

video=cv2.VideoCapture(0)

a=0

while True:
  a= a + 1
  check, frame = video.read()

  print(check)
  print(frame)

  gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

  cv2.imshow("captureing",gray)

  #cv2.witKey(0)

  key=cv2.witKey(1)

  if Key == ord('q'):
    break 

print(a)
video.release()

cv2.destroyAllWindows


